#!/bin/sh

if [[ "$(uname)" != "Darwin" ]]; then
  echo "Not on macOS, exiting..."
  exit 1
fi

HOSTNAME=bosch
sudo scutil --set ComputerName "$HOSTNAME"
sudo scutil --set HostName "$HOSTNAME"
sudo scutil --set LocalHostName "$HOSTNAME"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$HOSTNAME"

